/**
 * @file ui_comp_hook.c
 * @brief SquareLine Studio-generated UI hook file.
 *
 * This file is reserved for UI component hook integration and is kept as a
 * generated stub unless project-specific hook code is added.
 *
 * @ingroup UI
 */

// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project
