// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#include "Main_UI.h"
#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
void ui_update_task(void);
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);

// CUSTOM VARIABLES
extern lv_obj_t * uic_WiFi;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

