// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *uic_WiFi;
lv_obj_t *ui_Screen1 = NULL;
lv_obj_t *ui_WiFi = NULL;
lv_obj_t *ui_Label1 = NULL;
lv_obj_t *ui_TabView1 = NULL;
lv_obj_t *ui_TabPage1 = NULL;
lv_obj_t *ui_Label3 = NULL;
lv_obj_t *ui_Label5 = NULL;
lv_obj_t *ui_Label4 = NULL;
lv_obj_t *ui_Arc3 = NULL;
lv_obj_t *ui_Arc2 = NULL;
lv_obj_t *ui_Arc1 = NULL;
lv_obj_t *ui_TabPage2 = NULL;
lv_obj_t *ui_Chart1 = NULL;
lv_obj_t *ui_TabPage3 = NULL;
lv_obj_t *ui_Chart2 = NULL;
lv_obj_t *ui_Image2 = NULL;
// event funtions

// build funtions

char selected_ssid[64];

void kb_event_cb(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * kb = lv_event_get_target(e);
    lv_obj_t * ta = lv_event_get_user_data(e);

    if(code == LV_EVENT_READY)   // user pressed OK
    {
        const char *pass = lv_textarea_get_text(ta);


        WiFi_Connect(selected_ssid, pass);

        // cleanup UI
        lv_obj_del(kb);
        lv_obj_del(ta);
    }

    if(code == LV_EVENT_CANCEL)
    {
        lv_obj_del(kb);
        lv_obj_del(ta);
    }
}

void wifi_dropdown_cb(lv_event_t *event)
{
    lv_obj_t *obj = lv_event_get_target(event);

    lv_dropdown_get_selected_str(obj, selected_ssid, sizeof(selected_ssid));

    // Create textarea
    lv_obj_t *ta = lv_textarea_create(lv_scr_act());
    lv_obj_set_width(ta, 200);
    lv_obj_align(ta, LV_ALIGN_CENTER, 0, -40);

    lv_textarea_set_password_mode(ta, true);
    lv_textarea_set_placeholder_text(ta, "Enter password");

    // Create keyboard
    lv_obj_t *kb = lv_keyboard_create(lv_scr_act());
    lv_obj_set_size(kb, LV_HOR_RES, 120);
    lv_obj_align(kb, LV_ALIGN_BOTTOM_MID, 0, 0);

    lv_keyboard_set_textarea(kb, ta);

    // 👇 Attach keyboard event (IMPORTANT)
    lv_obj_add_event_cb(kb, kb_event_cb, LV_EVENT_ALL, ta);
}




void ui_Screen1_screen_init(WiFi *_WiFi)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_WiFi = lv_dropdown_create(ui_Screen1);
    lv_obj_set_width(ui_WiFi, 150);
    lv_obj_set_height(ui_WiFi, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_WiFi, 410);
    lv_obj_set_y(ui_WiFi, -229);
    lv_obj_set_align(ui_WiFi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_dropdown_clear_options(ui_WiFi);

    for (int i = 0; i < _WiFi->number; i++)
    {
        lv_dropdown_add_option(ui_WiFi, (char *)_WiFi->ap_info[i].ssid, LV_DROPDOWN_POS_LAST);
    }

    lv_obj_add_event_cb(ui_WiFi, wifi_dropdown_cb, LV_EVENT_VALUE_CHANGED, NULL);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label1, -6);
    lv_obj_set_y(ui_Label1, -233);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "GLENNERGY");
    lv_obj_set_style_text_letter_space(ui_Label1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView1 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView1, 959);
    lv_obj_set_height(ui_TabView1, 470);
    lv_obj_set_x(ui_TabView1, 0);
    lv_obj_set_y(ui_TabView1, 36);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_TabView1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage1 = lv_tabview_add_tab(ui_TabView1, "HOME");
    lv_obj_set_style_bg_color(ui_TabPage1, lv_color_hex(0x1E1425), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPage1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label3, -321);
    lv_obj_set_y(ui_Label3, -79);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "23.7°");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label5, 315);
    lv_obj_set_y(ui_Label5, -77);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "1013 hPa");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label4, 5);
    lv_obj_set_y(ui_Label4, -83);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "13.7%");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc3 = lv_arc_create(ui_TabPage1);
    lv_obj_set_width(ui_Arc3, 226);
    lv_obj_set_height(ui_Arc3, 214);
    lv_obj_set_x(ui_Arc3, 34);
    lv_obj_set_y(ui_Arc3, -66);
    lv_obj_set_align(ui_Arc3, LV_ALIGN_LEFT_MID);
    lv_arc_set_value(ui_Arc3, 50);
    lv_obj_set_style_border_color(ui_Arc3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Arc3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc3, lv_color_hex(0xC86868), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc3, lv_color_hex(0xC36A6A), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Arc2 = lv_arc_create(ui_TabPage1);
    lv_obj_set_width(ui_Arc2, 226);
    lv_obj_set_height(ui_Arc2, 214);
    lv_obj_set_x(ui_Arc2, 323);
    lv_obj_set_y(ui_Arc2, -63);
    lv_obj_set_align(ui_Arc2, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc2, 50);

    lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0x95C08B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc2, lv_color_hex(0x95C08B), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Arc1 = lv_arc_create(ui_TabPage1);
    lv_obj_set_width(ui_Arc1, 226);
    lv_obj_set_height(ui_Arc1, 214);
    lv_obj_set_x(ui_Arc1, -339);
    lv_obj_set_y(ui_Arc1, -64);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_RIGHT_MID);
    lv_arc_set_value(ui_Arc1, 50);

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "ELECTRICITY");
    lv_obj_set_style_bg_color(ui_TabPage2, lv_color_hex(0x1E1425), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPage2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_TabPage2, lv_color_hex(0x1E1425), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_TabPage2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart1 = lv_chart_create(ui_TabPage2);
    lv_obj_set_width(ui_Chart1, 740);
    lv_obj_set_height(ui_Chart1, 333);
    lv_obj_set_x(ui_Chart1, 3);
    lv_obj_set_y(ui_Chart1, -12);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t *ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x808080),
                                                                LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart1_series_1_array[] = {0, 10, 20, 40, 80, 80, 40, 20, 10, 0};
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);

    ui_TabPage3 = lv_tabview_add_tab(ui_TabView1, "WEATHER");
    lv_obj_set_style_bg_color(ui_TabPage3, lv_color_hex(0x1E1425), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPage3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart2 = lv_chart_create(ui_TabPage3);
    lv_obj_set_width(ui_Chart2, 646);
    lv_obj_set_height(ui_Chart2, 282);
    lv_obj_set_x(ui_Chart2, -26);
    lv_obj_set_y(ui_Chart2, 28);
    lv_obj_set_align(ui_Chart2, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart2, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t *ui_Chart2_series_1 = lv_chart_add_series(ui_Chart2, lv_color_hex(0x808080),
                                                                LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart2_series_1_array[] = {0, 10, 20, 40, 80, 80, 40, 20, 10, 0};
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_1, ui_Chart2_series_1_array);

    ui_Image2 = lv_img_create(ui_TabPage3);
    lv_img_set_src(ui_Image2, &ui_img_1286710220);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image2, 369);
    lv_obj_set_y(ui_Image2, -99);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_zoom(ui_Image2, 50);

    uic_WiFi = ui_WiFi;
}

void ui_Screen1_screen_destroy(void)
{
    if (ui_Screen1)
        lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    uic_WiFi = NULL;
    ui_WiFi = NULL;
    ui_Label1 = NULL;
    ui_TabView1 = NULL;
    ui_TabPage1 = NULL;
    ui_Label3 = NULL;
    ui_Label5 = NULL;
    ui_Label4 = NULL;
    ui_Arc3 = NULL;
    ui_Arc2 = NULL;
    ui_Arc1 = NULL;
    ui_TabPage2 = NULL;
    ui_Chart1 = NULL;
    ui_TabPage3 = NULL;
    ui_Chart2 = NULL;
    ui_Image2 = NULL;
}
