// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
void ui_update_task(void);
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Glennergy_Label;
extern lv_obj_t * ui_Tab_Main;
extern lv_obj_t * ui_TabPage_Home;
extern lv_obj_t * ui_TabPage_Electricity;
extern lv_obj_t * ui_Chart_Electricity;
extern lv_obj_t * ui_TabPage_Weather;
extern lv_obj_t * ui_Chart_Weather;
extern lv_obj_t * ui_TabPage_Settings;
extern lv_obj_t * ui_Group_Settings; 
extern lv_obj_t * ui_TabPage_WiFi;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
// CUSTOM VARIABLES
extern lv_obj_t * uic_WiFi;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

