// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "../Tabs/Settings/WiFi_UI.h"
#include "../Tabs/Home/Sensor_UI.h"

lv_obj_t *ui_Screen1 = NULL;
lv_obj_t *ui_Glennergy_Label = NULL;
lv_obj_t *ui_Tab_Main = NULL;
lv_obj_t *ui_TabPage_Home = NULL;
lv_obj_t *ui_TabPage_Electricity = NULL;
lv_obj_t *ui_Chart_Electricity = NULL;
lv_obj_t *ui_TabPage_Weather = NULL;
lv_obj_t *ui_Chart_Weather = NULL;
lv_obj_t *ui_TabPage_Settings = NULL;
lv_obj_t *ui_Group_Settings = NULL;
lv_obj_t *ui_TabPage_WiFi = NULL;
lv_obj_t *ui_Label2 = NULL;
lv_obj_t *ui_Label8 = NULL;
lv_obj_t *ui_Bar1 = NULL;
lv_obj_t *ui_Label9 = NULL;
lv_obj_t *ui_Label10 = NULL;
// event funtions

// build funtions

static const char *TAG = "UI";

void ui_update_task(void)
{
    while (1)
    {
        WiFi_UI_Update();
        Sensor_UI_Update();
        vTaskDelay(pdMS_TO_TICKS(10));
    }
}

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Glennergy_Label = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Glennergy_Label, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Glennergy_Label, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Glennergy_Label, -6);
    lv_obj_set_y(ui_Glennergy_Label, -233);
    lv_obj_set_align(ui_Glennergy_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Glennergy_Label, "GLENNERGY");
    lv_obj_set_style_text_letter_space(ui_Glennergy_Label, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Glennergy_Label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Glennergy_Label, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Glennergy_Label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tab_Main = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_Tab_Main, 959);
    lv_obj_set_height(ui_Tab_Main, 470);
    lv_obj_set_x(ui_Tab_Main, 0);
    lv_obj_set_y(ui_Tab_Main, 36);
    lv_obj_set_align(ui_Tab_Main, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Tab_Main, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_MOMENTUM); /// Flags
    lv_obj_set_style_bg_color(ui_Tab_Main, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Tab_Main, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_Tab_Main), lv_color_hex(0x975EED),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_Tab_Main), 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(lv_tabview_get_tab_btns(ui_Tab_Main), lv_color_hex(0x4B3B5E),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(lv_tabview_get_tab_btns(ui_Tab_Main), LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_Tab_Main), lv_color_hex(0x6D2AB2),
                              LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_Tab_Main), 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(lv_tabview_get_tab_btns(ui_Tab_Main), lv_color_hex(0x000000),
                                   LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(lv_tabview_get_tab_btns(ui_Tab_Main), LV_GRAD_DIR_VER, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_TabPage_Home = lv_tabview_add_tab(ui_Tab_Main, "HOME");
    lv_obj_set_style_bg_color(ui_TabPage_Home, lv_color_hex(0x1E1425), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPage_Home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_TabPage_Home, lv_color_hex(0x301E4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_TabPage_Home, 254, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_TabPage_Home, 999, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_TabPage_Home, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TabPage_Home, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TabPage_Home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TabPage_Home, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TabPage_Home, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TabPage_Home, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TabPage_Home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage_Electricity = lv_tabview_add_tab(ui_Tab_Main, "ELECTRICITY");
    lv_obj_set_style_bg_color(ui_TabPage_Electricity, lv_color_hex(0x1E1425), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPage_Electricity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_TabPage_Electricity, lv_color_hex(0x1E1425), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_TabPage_Electricity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart_Electricity = lv_chart_create(ui_TabPage_Electricity);
    lv_obj_set_width(ui_Chart_Electricity, 689);
    lv_obj_set_height(ui_Chart_Electricity, 285);
    lv_obj_set_x(ui_Chart_Electricity, 3);
    lv_obj_set_y(ui_Chart_Electricity, 20);
    lv_obj_set_align(ui_Chart_Electricity, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart_Electricity, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_Chart_Electricity, 24);
    lv_chart_set_axis_tick(ui_Chart_Electricity, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart_Electricity, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart_Electricity, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t *ui_Chart1_series_1 = lv_chart_add_series(ui_Chart_Electricity, lv_color_hex(0x808080),
                                                                LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart1_series_1_array[] = {0, 10, 20, 40, 80, 80, 40, 20, 10, 0};
    lv_chart_set_ext_y_array(ui_Chart_Electricity, ui_Chart1_series_1, ui_Chart1_series_1_array);
    lv_obj_set_style_bg_color(ui_Chart_Electricity, lv_color_hex(0x20142F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart_Electricity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Chart_Electricity, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_Chart_Electricity, lv_color_hex(0x9240FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart_Electricity, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Chart_Electricity, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Chart_Electricity, 255, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_TabPage_Weather = lv_tabview_add_tab(ui_Tab_Main, "WEATHER");
    lv_obj_set_style_bg_color(ui_TabPage_Weather, lv_color_hex(0x1E1425), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPage_Weather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart_Weather = lv_chart_create(ui_TabPage_Weather);
    lv_obj_set_width(ui_Chart_Weather, 689);
    lv_obj_set_height(ui_Chart_Weather, 285);
    lv_obj_set_x(ui_Chart_Weather, 3);
    lv_obj_set_y(ui_Chart_Weather, 200);
    lv_obj_set_align(ui_Chart_Weather, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart_Weather, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_Chart_Weather, 24);
    lv_chart_set_axis_tick(ui_Chart_Weather, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart_Weather, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart_Weather, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t *ui_Chart3_series_1 = lv_chart_add_series(ui_Chart_Weather, lv_color_hex(0x808080),
                                                                LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart3_series_1_array[] = {0, 10, 20, 40, 80, 80, 40, 20, 10, 0};
    lv_chart_set_ext_y_array(ui_Chart_Weather, ui_Chart3_series_1, ui_Chart3_series_1_array);
    lv_obj_set_style_bg_color(ui_Chart_Weather, lv_color_hex(0x20142F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart_Weather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Chart_Weather, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_Chart_Weather, lv_color_hex(0x9240FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart_Weather, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage_Settings = lv_tabview_add_tab(ui_Tab_Main, "SETTINGS");
    lv_obj_set_style_bg_color(ui_TabPage_Settings, lv_color_hex(0x1E1425), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPage_Settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Settings = lv_obj_create(ui_TabPage_Settings);

    lv_obj_set_width(ui_Group_Settings, 404);
    lv_obj_set_height(ui_Group_Settings, 380);
    lv_obj_set_x(ui_Group_Settings, -263);
    lv_obj_set_y(ui_Group_Settings, -5);
    lv_obj_set_align(ui_Group_Settings, LV_ALIGN_CENTER);

    // Match your "non-scrollable" behavior
    lv_obj_clear_flag(ui_Group_Settings,
                      LV_OBJ_FLAG_SCROLLABLE |
                          LV_OBJ_FLAG_SCROLL_ELASTIC |
                          LV_OBJ_FLAG_SCROLL_MOMENTUM |
                          LV_OBJ_FLAG_SCROLL_CHAIN);

    // Style (based on your tab button style)
    lv_obj_set_style_bg_color(ui_Group_Settings, lv_color_hex(0x6E10CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Group_Settings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Group_Settings, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Optional: cleaner edges (tabview had implicit styling)
    lv_obj_set_style_radius(ui_Group_Settings, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Group_Settings, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Group_Settings, lv_color_hex(0x6E10CE), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Group_Settings);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label2, -163);
    lv_obj_set_y(ui_Label2, -131);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "WiFi");
    
    Sensor_UI_Initialize();

    WiFi_UI_Initialize();

    ui_Label9 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label9, 408);
    lv_obj_set_y(ui_Label9, -258);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "WiFi");
    lv_obj_set_style_text_letter_space(ui_Label9, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label9, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label10, 410);
    lv_obj_set_y(ui_Label10, -233);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "NetGear");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x00FF07), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void ui_Screen1_screen_destroy(void)
{
    if (ui_Screen1)
        lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Glennergy_Label = NULL;
    ui_Tab_Main = NULL;
    ui_TabPage_Home = NULL;
    ui_TabPage_Electricity = NULL;
    ui_Chart_Electricity = NULL;
    ui_TabPage_Weather = NULL;
    ui_Chart_Weather = NULL;
    ui_TabPage_Settings = NULL;
    ui_TabPage_WiFi = NULL;
    ui_Label2 = NULL;
    ui_Label8 = NULL;
    ui_Bar1 = NULL;
    ui_Label9 = NULL;
    ui_Label10 = NULL;
}

/*void ui_Screen1_screen_init()
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label1, -6);
    lv_obj_set_y(ui_Label1, -233);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "GLENNERGY");
    lv_obj_set_style_text_letter_space(ui_Label1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView1 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView1, 959);
    lv_obj_set_height(ui_TabView1, 470);
    lv_obj_set_x(ui_TabView1, 0);
    lv_obj_set_y(ui_TabView1, 36);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_TabView1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage1 = lv_tabview_add_tab(ui_TabView1, "HOME");
    lv_obj_set_style_bg_color(ui_TabPage1, lv_color_hex(0x1E1425), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPage1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label3, -321);
    lv_obj_set_y(ui_Label3, -79);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "23.7°");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label5, 315);
    lv_obj_set_y(ui_Label5, -77);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "1013 hPa");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label4, 5);
    lv_obj_set_y(ui_Label4, -83);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "13.7%");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc3 = lv_arc_create(ui_TabPage1);
    lv_obj_set_width(ui_Arc3, 226);
    lv_obj_set_height(ui_Arc3, 214);
    lv_obj_set_x(ui_Arc3, 34);
    lv_obj_set_y(ui_Arc3, -66);
    lv_obj_set_align(ui_Arc3, LV_ALIGN_LEFT_MID);
    lv_arc_set_value(ui_Arc3, 50);
    lv_obj_set_style_border_color(ui_Arc3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Arc3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc3, lv_color_hex(0xC86868), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc3, lv_color_hex(0xC36A6A), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Arc2 = lv_arc_create(ui_TabPage1);
    lv_obj_set_width(ui_Arc2, 226);
    lv_obj_set_height(ui_Arc2, 214);
    lv_obj_set_x(ui_Arc2, 323);
    lv_obj_set_y(ui_Arc2, -63);
    lv_obj_set_align(ui_Arc2, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc2, 50);

    lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0x95C08B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc2, lv_color_hex(0x95C08B), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Arc1 = lv_arc_create(ui_TabPage1);
    lv_obj_set_width(ui_Arc1, 226);
    lv_obj_set_height(ui_Arc1, 214);
    lv_obj_set_x(ui_Arc1, -339);
    lv_obj_set_y(ui_Arc1, -64);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_RIGHT_MID);
    lv_arc_set_value(ui_Arc1, 50);

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "ELECTRICITY");
    lv_obj_set_style_bg_color(ui_TabPage2, lv_color_hex(0x1E1425), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPage2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_TabPage2, lv_color_hex(0x1E1425), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_TabPage2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart1 = lv_chart_create(ui_TabPage2);
    lv_obj_set_width(ui_Chart1, 740);
    lv_obj_set_height(ui_Chart1, 333);
    lv_obj_set_x(ui_Chart1, 3);
    lv_obj_set_y(ui_Chart1, -12);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t *ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x808080),
                                                                LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart1_series_1_array[] = {0, 10, 20, 40, 80, 80, 40, 20, 10, 0};
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);

    ui_TabPage3 = lv_tabview_add_tab(ui_TabView1, "WEATHER");
    lv_obj_set_style_bg_color(ui_TabPage3, lv_color_hex(0x1E1425), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPage3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart2 = lv_chart_create(ui_TabPage3);
    lv_obj_set_width(ui_Chart2, 646);
    lv_obj_set_height(ui_Chart2, 282);
    lv_obj_set_x(ui_Chart2, -26);
    lv_obj_set_y(ui_Chart2, 28);
    lv_obj_set_align(ui_Chart2, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart2, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t *ui_Chart2_series_1 = lv_chart_add_series(ui_Chart2, lv_color_hex(0x808080),
                                                                LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart2_series_1_array[] = {0, 10, 20, 40, 80, 80, 40, 20, 10, 0};
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_1, ui_Chart2_series_1_array);

    ui_Image2 = lv_img_create(ui_TabPage3);
    lv_img_set_src(ui_Image2, &ui_img_1286710220);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image2, 369);
    lv_obj_set_y(ui_Image2, -99);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_zoom(ui_Image2, 50);

    ui_TabPage4 = lv_tabview_add_tab(ui_TabView1, "SETTINGS");
    lv_obj_set_style_bg_color(ui_TabPage4, lv_color_hex(0x1E1425), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPage4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView2 = lv_tabview_create(ui_TabPage4, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView2, 404);
    lv_obj_set_height(ui_TabView2, 380);
    lv_obj_set_x(ui_TabView2, -263);
    lv_obj_set_y(ui_TabView2, -5);
    lv_obj_set_align(ui_TabView2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_TabPage5 = lv_tabview_add_tab(ui_TabView2, "WiFi");

    ui_Label2 = lv_label_create(ui_TabPage5);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label2, -163);
    lv_obj_set_y(ui_Label2, -131);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "WiFi");

    ui_WiFi = lv_dropdown_create(ui_TabPage5);
    lv_obj_set_width(ui_WiFi, 368);
    lv_obj_set_height(ui_WiFi, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_WiFi, 4);
    lv_obj_set_y(ui_WiFi, -83);
    lv_obj_set_align(ui_WiFi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFi, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags

    if (wifi_queue != NULL)
    {
        ESP_LOGI(TAG, "WIFI QUEUE PASS");
        if (xQueueReceive(wifi_queue, &wifi, portMAX_DELAY) == pdPASS)
        {
        }
    }

    // ESP_LOGI(TAG, "NETWORKS: %d", wifi->number);

    lv_obj_add_event_cb(ui_WiFi, wifi_dropdown_cb, LV_EVENT_VALUE_CHANGED, NULL);

    ui_TextArea1 = lv_textarea_create(ui_TabPage5);
    lv_obj_set_width(ui_TextArea1, 368);
    lv_obj_set_height(ui_TextArea1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_TextArea1, 2);
    lv_obj_set_y(ui_TextArea1, -26);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Password");
    lv_textarea_set_one_line(ui_TextArea1, true);
    lv_textarea_set_password_mode(ui_TextArea1, true);

    lv_obj_add_event_cb(ui_TextArea1, textarea_cb, LV_EVENT_CLICKED, NULL);

    ui_Label6 = lv_label_create(ui_TabPage5);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label6, -308);
    lv_obj_set_y(ui_Label6, -107);
    lv_obj_set_align(ui_Label6, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Label6, "Status: ");

    ui_Label7 = lv_label_create(ui_TabPage5);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label7, -200);
    lv_obj_set_y(ui_Label7, -107);
    lv_obj_set_align(ui_Label7, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Label7, "Disconnected");
    lv_label_set_recolor(ui_Label7, "true");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_TabPage5);
    lv_obj_set_width(ui_Button3, 50);
    lv_obj_set_height(ui_Button3, 25);
    lv_obj_set_x(ui_Button3, -47);
    lv_obj_set_y(ui_Button3, -133);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x1E1425), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button3, wifi_scan_cb, LV_EVENT_PRESSED, NULL);

    ui_Label8 = lv_label_create(ui_TabPage5);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label8, -48);
    lv_obj_set_y(ui_Label8, -133);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "SCAN");

    ui_Bar1 = lv_bar_create(ui_TabPage5);
    lv_bar_set_value(ui_Bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 150);
    lv_obj_set_height(ui_Bar1, 10);
    lv_obj_set_x(ui_Bar1, 69);
    lv_obj_set_y(ui_Bar1, -133);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

    uic_WiFi = ui_WiFi;
}*/