// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#include "../../main/WiFi.h"
#include "../../main/UART/fake_sensor.hpp"

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init();
extern void ui_Screen1_screen_destroy(void);
extern void ui_update_task(void *arg);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_WiFi;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Arc3;
extern lv_obj_t * ui_Arc2;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_TabPage3;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_Image2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_WiFi;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

