// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

/**
 * @file ui.h
 * @brief Public UI entry points and generated screen declarations.
 *
 * This header exposes the generated LVGL objects and UI lifecycle functions
 * used to initialize and destroy the SquareLine-generated interface.
 *
 * @ingroup UI
 */

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "lvgl_port.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


/**
 * @brief Generated initial action object used by the UI startup sequence.
 */
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1286710220);    // assets/8e9fc233-7db3-4144-9197-476dcfcd7fda.png

/**
 * @brief Initializes the generated UI.
 */
void ui_init();

/**
 * @brief Destroys the generated UI.
 */
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
