/**
 * @file ui_events.h
 * @brief LVGL event declarations for the UI generated by SquareLine Studio.
 *
 * This header is kept as the generated integration point for UI event hooks.
 * It currently does not declare any event handlers.
 */

/**
 * @defgroup UI_EVENTS UI_EVENTS
 * @brief LVGL UI event hook declarations.
 *
 * Generated integration header for UI event callbacks used by the SquareLine
 * Studio project.
 */

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
